name: Bot3
on:
  push:
    branches: [stag4]

env:
  TZ: America/Recife
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 525600

    steps:
      - name: Checkouts
        uses: actions/checkout@master
          
      - name: Try to drop prebuilt OpenJDKs
        run: |
          rm -rf /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
          sudo apt-get purge --purge adoptopenjdk* msopenjdk* openjdk-11* openjdk-13* openjdk-16* openjdk-17* openjdk-8* openjdk* -y
      
      - name: Check prebuilt OpenJDKs
        run: |
          apt list | grep openjdk

      - name: Try to install GraalVM's JDK 16
        run: |
          sudo su
          cd /usr && mkdir -p oracle/java
          wget 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java16-linux-amd64-21.2.0.tar.gz' -O graalvm-jdk16.tar.gz >> /dev/null 2>&1
          tar -xzvf graalvm-jdk16.tar.gz >> /dev/null 2>&1 && rm -f graalvm-jdk16.tar.gz
          ls
