name: Bot3
on:
  push:
    branches: [stag4]

env:
  TZ: America/Recife
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 525600

    steps:
      - name: Checkouts
        uses: actions/checkout@master
          
      - name: Try to drop prebuilt OpenJDKs
        run: |
          rm -rf /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
          sudo apt-get purge --purge adoptopenjdk* msopenjdk* openjdk-11* openjdk-13* openjdk-16* openjdk-17* openjdk-8* openjdk* -y
      
      - name: Install OpenJDK 8 # ROM_resigner/signapk.jar really need it (We've to reset two commits) 
        run: |
          sudo apt install openjdk-8-jdk -y

      - name: Try to download GraalVM's JDK 17
        run: |
          cd /usr; sudo mkdir -p oracle/java/ && cd oracle/java/
          sudo wget 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java17-linux-amd64-21.3.0.tar.gz' -O graalvm-jdk17.tar.gz >> /dev/null 2>&1
          sudo tar -xzvf graalvm-jdk17.tar.gz >> /dev/null 2>&1 && sudo rm -f graalvm-jdk17.tar.gz
          export JAVA_HOME=/usr/oracle/java/graalvm-ce-java17-21.3.0
          export PATH=$PATH:$JAVA_HOME/bin
      
      - name: Set GraalVM as default
        run: |
          sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/oracle/java/graalvm-ce-java17-21.3.0/bin/javac" 1
          sudo update-alternatives --install "/usr/bin/java" "java" "/usr/oracle/java/graalvm-ce-java17-21.3.0/bin/java" 1
          sudo update-alternatives --install "/usr/bin/gu" "gu" "/usr/oracle/java/graalvm-ce-java17-21.3.0/bin/gu" 1
    
      - name: Check if OpenJDK is set as default
        run: |
          java -version
      
      - name: Clone & Compile Bot³+t
        env:
          JAVA_HOME: /usr/oracle/java/graalvm-ce-java17-21.3.0
        run: |
          git clone https://github.com/TrebleExperience/Bot3
          cd Bot3 && ./gradlew shadowJar
          
      - name: Install native-image & Rebuild Bot³+t prebuilt Jar as native code
        run: |
          sudo gu install native-image
          sudo update-alternatives --install "/usr/bin/native-image" "native-image" "/usr/oracle/java/graalvm-ce-java17-21.3.0/bin/native-image" 1
          cd Bot3/build/libs && native-image -jar *.jar
          ./BoboBot-1.7.0-all
